// Privacy filters of the capture pipeline (spec §5.1 / §9): pause, ignored apps, pasteboard flags,
// user regexps and high-confidence secret patterns. Returns a skip reason, never the content itself.
import type { ClipboardSettings } from '@/lib/clipboard/types'

export type PrivacyFlags = {
  concealed: boolean
  transient: boolean
  autoGenerated: boolean
}

export type PrivacyPrecheckInput = {
  settings: ClipboardSettings
  now: number
  sourceBundleId?: string
  frontmostBundleId?: string
  flags: PrivacyFlags
}

/** Only scan the head of very large texts; secrets are short and usually at the start. */
const SECRET_SCAN_MAX_CHARS = 100_000

// High-confidence secret shapes, modelled on EcoPaste's secrets.rs. Each one is precise enough that a match
// is very unlikely to be ordinary prose, so it is safe to drop the copy without asking.
export const SECRET_PATTERNS: Array<{ name: string; pattern: RegExp }> = [
  { name: 'pem-private-key', pattern: /-----BEGIN (?:[A-Z]+ )*PRIVATE KEY(?: BLOCK)?-----/ },
  { name: 'github-token', pattern: /\bgh[pousr]_[A-Za-z0-9]{36,}\b/ },
  { name: 'github-fine-grained-pat', pattern: /\bgithub_pat_[A-Za-z0-9_]{22,}\b/ },
  { name: 'openai-style-key', pattern: /\bsk-(?:proj-|ant-[a-z\d]+-)?(?=[A-Za-z0-9_-]*\d)[A-Za-z0-9_-]{20,}/ },
  { name: 'slack-token', pattern: /\bxox[abprso]-[A-Za-z0-9-]{10,}/ },
  { name: 'aws-access-key-id', pattern: /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/ },
  { name: 'jwt', pattern: /\beyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}/ },
  {
    name: 'labeled-secret',
    pattern:
      /\b(?:api[_-]?key|secret(?:[_-]?key)?|access[_-]?token|auth[_-]?token|token|passw(?:or)?d|pwd)\s*[:=]\s*["']?[A-Za-z0-9_\-/+=.]{16,}/i,
  },
]

const compiledUserPatterns = new Map<string, RegExp | null>()

const compileUserPattern = (source: string): RegExp | null => {
  if (compiledUserPatterns.has(source)) {
    return compiledUserPatterns.get(source) ?? null
  }

  let compiled: RegExp | null = null
  try {
    compiled = new RegExp(source)
  } catch {
    compiled = null
  }
  compiledUserPatterns.set(source, compiled)
  return compiled
}

export const isPaused = (settings: ClipboardSettings, now: number) =>
  settings.pausedUntil === -1 || (settings.pausedUntil > 0 && settings.pausedUntil > now)

/** Checks that need no content: master switch, pause, ignored apps and nspasteboard flags. */
export const checkPrivacyPrecondition = (input: PrivacyPrecheckInput): string | null => {
  const { settings, now, flags } = input

  if (!settings.enabled) {
    return 'disabled'
  }

  if (isPaused(settings, now)) {
    return 'paused'
  }

  const ignored = new Set(settings.privacy.ignoredBundleIds.map((id) => id.toLowerCase()))
  for (const bundleId of [input.sourceBundleId, input.frontmostBundleId]) {
    if (bundleId && ignored.has(bundleId.toLowerCase())) {
      return 'ignored-app'
    }
  }

  if (flags.concealed && settings.privacy.ignoreConfidential) {
    return 'concealed'
  }

  if (flags.transient && settings.privacy.ignoreTransient) {
    return 'transient'
  }

  // The settings model has no separate switch for auto-generated content; it follows the transient one.
  if (flags.autoGenerated && settings.privacy.ignoreTransient) {
    return 'auto-generated'
  }

  return null
}

export const findSecretPattern = (text: string): string | null => {
  const sample = text.length > SECRET_SCAN_MAX_CHARS ? text.slice(0, SECRET_SCAN_MAX_CHARS) : text
  for (const { name, pattern } of SECRET_PATTERNS) {
    if (pattern.test(sample)) {
      return name
    }
  }
  return null
}

/** Content checks: user regexps first, then built-in secret detection. */
export const checkPrivacyContent = (settings: ClipboardSettings, texts: string[]): string | null => {
  for (const text of texts) {
    if (!text) {
      continue
    }

    for (const source of settings.privacy.ignoreRegexps) {
      if (source && compileUserPattern(source)?.test(text)) {
        return 'user-regexp'
      }
    }

    if (settings.privacy.detectSecrets) {
      const secret = findSecretPattern(text)
      if (secret) {
        return `secret:${secret}`
      }
    }
  }

  return null
}
