// Pasteboard polling and the capture pipeline (spec §5.1): 250 ms changeCount poll, one snapshot read,
// privacy filters, normalize + classify + fingerprint, ingest. Clipboard content is never logged.
import { decodeClipboardImage } from '@/lib/clipboard/capture/image'
import { buildIngestRecord, candidateTexts, extractCandidate } from '@/lib/clipboard/capture/normalize'
import { PASTEBOARD_ALLOW_TYPES, isOfficeLinkCopy } from '@/lib/clipboard/capture/pasteboard-types'
import { checkPrivacyContent, checkPrivacyPrecondition } from '@/lib/clipboard/capture/privacy'
import { enrichQueue } from '@/lib/clipboard/enrich/queue'
import { clipboardNative } from '@/lib/clipboard/native-bridge'
import { clipStore } from '@/lib/clipboard/store'
import type { ClipboardSettings } from '@/lib/clipboard/types'
import { mainLogger } from '@/lib/main/logger'

const POLL_INTERVAL_MS = 250
const TEXT_PICKER_RESTORE_MARKER = 'text-picker-restore'
const ITEM_ID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

export type ClipboardWatcherDeps = {
  getSettings: () => ClipboardSettings
}

const round = (value: number) => Math.round(value * 10) / 10

export class ClipboardWatcher {
  private timer: NodeJS.Timeout | null = null
  private lastChangeCount = -1
  private busy = false
  private deps: ClipboardWatcherDeps | null = null

  start(deps: ClipboardWatcherDeps) {
    if (this.timer) {
      return
    }

    this.deps = deps
    if (!clipboardNative.isSupported()) {
      mainLogger.warn('[clip-capture] native pasteboard access is not available, capture disabled')
      return
    }

    // Content that was already on the pasteboard at launch is not history; only new copies are.
    this.lastChangeCount = clipboardNative.getChangeCount()
    this.timer = setInterval(() => void this.poll(), POLL_INTERVAL_MS)
    this.timer.unref()
    mainLogger.info('[clip-capture] started', { pollMs: POLL_INTERVAL_MS, changeCount: this.lastChangeCount })
  }

  stop() {
    if (this.timer) {
      clearInterval(this.timer)
      this.timer = null
      mainLogger.info('[clip-capture] stopped')
    }
  }

  private async poll() {
    if (this.busy || !this.deps) {
      return
    }

    const changeCount = clipboardNative.getChangeCount()
    if (changeCount < 0 || changeCount === this.lastChangeCount) {
      return
    }

    // The selection fallback simulates ⌘C and then restores the pasteboard. Leave lastChangeCount untouched so the
    // restored content (carrying the restore marker) is evaluated once the fallback is over.
    if (clipboardNative.isSelectionFallbackActive()) {
      return
    }

    this.busy = true
    try {
      await this.handleChange(changeCount, this.deps.getSettings())
    } catch (error) {
      mainLogger.warn('[clip-capture] capture failed', error)
    } finally {
      this.busy = false
    }
  }

  private skip(reason: string, data: Record<string, unknown> = {}) {
    mainLogger.info('[clip-capture] skipped', { reason, ...data })
  }

  private async handleChange(changeCount: number, settings: ClipboardSettings) {
    const startedAt = performance.now()
    this.lastChangeCount = changeCount
    const now = Date.now()

    // Cheap checks first: no need to touch the pasteboard while capture is off or paused.
    const preliminary = checkPrivacyPrecondition({
      settings,
      now,
      flags: { concealed: false, transient: false, autoGenerated: false },
    })
    if (preliminary) {
      this.skip(preliminary)
      return
    }

    const frontmost = clipboardNative.getFrontmostApp()
    const readStartedAt = performance.now()
    const snapshot = clipboardNative.read({
      allowTypes: PASTEBOARD_ALLOW_TYPES,
      maxBytes: Math.max(1, settings.maxItemMb) * 1024 * 1024,
    })
    const readMs = performance.now() - readStartedAt

    if (!snapshot) {
      this.skip('read-failed')
      return
    }

    // Use the snapshot's own count so a change that happened during the read is picked up by the next poll.
    this.lastChangeCount = snapshot.changeCount

    if (snapshot.popMindMarker) {
      if (ITEM_ID_PATTERN.test(snapshot.popMindMarker)) {
        await clipStore.markUsed(snapshot.popMindMarker)
        mainLogger.info('[clip-capture] own write-back, bumped item', {
          id: snapshot.popMindMarker,
          readMs: round(readMs),
        })
      } else {
        this.skip(snapshot.popMindMarker === TEXT_PICKER_RESTORE_MARKER ? 'text-picker-restore' : 'own-marker')
      }
      return
    }

    if (snapshot.tooLarge) {
      this.skip('too-large', { totalBytes: snapshot.totalBytes, limitMb: settings.maxItemMb })
      return
    }

    const blocked = checkPrivacyPrecondition({
      settings,
      now,
      sourceBundleId: snapshot.sourceBundleId,
      frontmostBundleId: frontmost?.bundleId,
      flags: snapshot.flags,
    })
    if (blocked) {
      this.skip(blocked, { sourceBundleId: snapshot.sourceBundleId, frontmostBundleId: frontmost?.bundleId })
      return
    }

    if (isOfficeLinkCopy(snapshot.allTypes)) {
      this.skip('office-link')
      return
    }

    const normalizeStartedAt = performance.now()
    const candidate = extractCandidate(snapshot.items)
    const contentBlocked = checkPrivacyContent(settings, candidateTexts(candidate))
    if (contentBlocked) {
      this.skip(contentBlocked)
      return
    }

    const bundleId = snapshot.sourceBundleId ?? frontmost?.bundleId
    const source = bundleId
      ? {
          bundleId,
          name:
            frontmost && frontmost.bundleId === bundleId && frontmost.name
              ? frontmost.name
              : (bundleId.split('.').pop() ?? bundleId),
        }
      : undefined

    const built = await buildIngestRecord(candidate, {
      copiedAt: now,
      source,
      isRemote: snapshot.flags.remote,
      maxBytes: Math.max(1, settings.maxItemMb) * 1024 * 1024,
      decodeImage: decodeClipboardImage,
    })
    const normalizeMs = performance.now() - normalizeStartedAt

    if (!built.ok) {
      this.skip(built.reason, { itemCount: snapshot.items.length })
      return
    }

    const storeStartedAt = performance.now()
    const outcome = await clipStore.ingest(built.record)
    const storeMs = performance.now() - storeStartedAt
    enrichQueue.notifyIngest(built.record.source)

    mainLogger.info('[clip-capture] ingested', {
      status: outcome.status,
      kind: built.record.kind,
      bytes: built.record.byteSize,
      items: snapshot.items.length,
      remote: built.record.isRemote,
      sourceBundleId: built.record.source?.bundleId,
      readMs: round(readMs),
      normalizeMs: round(normalizeMs),
      storeMs: round(storeMs),
      totalMs: round(performance.now() - startedAt),
    })
  }
}
