import { existsSync } from 'node:fs'
import { createRequire } from 'node:module'
import { resolve } from 'node:path'
import { app } from 'electron'
import { mainLogger } from '@/lib/main/logger'
import type { SelectionActionEvent, SelectionSceneValue, SelectionSnapshot } from '@/lib/text-picker/shared'

type ClipboardSnapshotType = {
  type: string
  data: Buffer
}

type ClipboardSnapshotItem = {
  types: ClipboardSnapshotType[]
}

export interface NativeMacOSAddon {
  checkPermission(prompt?: boolean): boolean
  getSelectionSnapshot(options?: { scene?: SelectionSceneValue | string }): SelectionSnapshot
  getTextByClipboardAsync(useMenu: boolean, pid: number): Promise<string>
  copySelectionAsync(useMenu: boolean, pid: number, expectedText?: string): Promise<boolean>
  captureFrontmostWindowImage(pid?: number): Buffer | null
  startActionMonitor(callback: (event: SelectionActionEvent) => void): boolean
  stopActionMonitor(): boolean
  setKeyMonitorEnabled(enabled: boolean): boolean
  getCursorPosition(): { x: number; y: number }
  getFrontmostAppInfo(): { bundleId: string; name: string; pid: number }
  getClipboardChangeCount(): number
  isClipboardFallbackActive?(): boolean
  getClipboardSnapshot(): ClipboardSnapshotItem[]
  restoreClipboardSnapshot(items: ClipboardSnapshotItem[]): boolean
  activateAppAndPaste(pid: number): boolean
  configureBubbleWindow(nativeHandle: Buffer): boolean
  orderBubbleFront(nativeHandle: Buffer): boolean
  setActivationPolicy(policy: number): boolean
  recognizeTextInImageAsync(imagePath: string): Promise<string>
  readApplicationsInfoAsync?(appPaths: string[], locales: string[]): Promise<NativeApplicationInfo[]>
  writeApplicationIconsAsync?(items: Array<{ appPath: string; outputPath: string }>, size: number): Promise<boolean[]>
  // ---- clipboard (docs/clipboard-paste-redesign.md §5) ----
  readPasteboard?(options: NativePasteboardReadOptions): NativePasteboardReadResult
  /** Decodes any ImageIO format (TIFF, HEIC, JPEG…) and re-encodes it as PNG on a worker thread. */
  convertImageToPngAsync?(data: Buffer): Promise<{ png: Buffer; width: number; height: number }>
  writePasteboard?(items: NativePasteboardItem[], options: NativePasteboardWriteOptions): boolean
  postPasteKeystroke?(): NativePasteKeystrokeResult
  /** Virtual key code that types "v" in the current keyboard layout (diagnostics; nothing is sent). */
  resolvePasteKeyCode?(): number
  isSecureInputEnabled?(): boolean
  presentPanelWithoutActivation?(nativeHandle: Buffer): boolean
  /** Per-window NSAppearance; 'inherit' follows the app theme again. */
  setWindowAppearance?(nativeHandle: Buffer, mode: 'dark' | 'light' | 'inherit'): boolean
  /** Rounds only the top corners of the window's vibrancy view (0 removes the mask). */
  setVibrancyTopCornerRadius?(nativeHandle: Buffer, radius: number): boolean
  startPasteMonitor?(callback: (event: NativePasteMonitorEvent) => void): boolean
  stopPasteMonitor?(): boolean
  resolveAppPathByBundleId?(bundleId: string): string | null
  recognizeTextInImageWithOptionsAsync?(imagePath: string, options: NativeOcrOptions): Promise<string>
}

export type NativePasteboardRepresentation = {
  /** UTI, e.g. `public.utf8-plain-text`. */
  type: string
  data: Buffer
}

/** One NSPasteboardItem. */
export type NativePasteboardItem = {
  representations: NativePasteboardRepresentation[]
}

export type NativePasteboardReadOptions = {
  /** Only these UTIs are read (reading others can force apps to render huge lazy data). */
  allowTypes: string[]
  /** Abort (return `tooLarge: true`, no items) when the allowed data exceeds this many bytes. */
  maxBytes: number
  /**
   * Separate budget for raw image data (png/tiff/jpeg/heic), which the caller re-encodes and size-checks itself.
   * A TIFF is skipped when the same item also offers a compressed image. Defaults to `maxBytes`.
   */
  maxImageBytes?: number
}

export type NativePasteboardReadResult = {
  changeCount: number
  items: NativePasteboardItem[]
  /** Union of every type on the pasteboard (read without loading data), used for flag detection. */
  allTypes: string[]
  flags: {
    /** org.nspasteboard.ConcealedType */
    concealed: boolean
    /** org.nspasteboard.TransientType or de.petermaurer.TransientPasteboardType */
    transient: boolean
    /** org.nspasteboard.AutoGeneratedType */
    autoGenerated: boolean
    /** com.apple.is-remote-clipboard (Universal Clipboard) */
    remote: boolean
  }
  /** String value of POPMIND_PASTEBOARD_MARKER when popMind wrote this content. */
  popMindMarker?: string
  /** String value of org.nspasteboard.source when the copying app declared itself. */
  sourceBundleId?: string
  tooLarge: boolean
  totalBytes: number
}

export type NativePasteboardWriteOptions = {
  /** Written as POPMIND_PASTEBOARD_MARKER on the first item. */
  marker: string
}

export type NativePasteKeystrokeResult = {
  ok: boolean
  reason?: 'no_permission' | 'secure_input'
}

/** Fired on key-up of a physical ⌘V (synthetic events posted by popMind are ignored). */
export type NativePasteMonitorEvent = {
  type: 'user-paste'
  timestamp: number
}

export type NativeOcrOptions = {
  /** BCP-47, default ['zh-Hans', 'zh-Hant', 'en-US']. */
  languages?: string[]
  /** true = VNRequestTextRecognitionLevelFast. Default accurate. */
  fast?: boolean
}

export interface NativeApplicationInfo {
  path: string
  bundleId: string
  name: string
  displayName: string
  /** Finder name in the current system language, without ".app". */
  fileDisplayName: string
  executable: string
  localizedNames: Record<string, string>
}

const require = createRequire(import.meta.url)

const resolveAddonPath = (): string | null => {
  const candidates = [
    resolve(process.cwd(), 'build/Release/selection_bridge.node'),
    resolve(process.resourcesPath, 'app.asar.unpacked/build/Release/selection_bridge.node'),
  ]

  try {
    candidates.push(resolve(app.getAppPath(), 'build/Release/selection_bridge.node'))
  } catch {
    // App path is unavailable before Electron finishes bootstrapping.
  }

  return candidates.find((candidate) => existsSync(candidate)) ?? null
}

const loadNativeModule = (): NativeMacOSAddon | null => {
  if (process.platform !== 'darwin') {
    return null
  }

  const addonPath = resolveAddonPath()
  if (!addonPath) {
    mainLogger.error('[macos-addon] native addon not found')
    return null
  }

  mainLogger.info('[macos-addon] resolved native addon', { addonPath })

  try {
    return require(addonPath) as NativeMacOSAddon
  } catch (error) {
    mainLogger.error('[macos-addon] failed to load native addon:', error)
    return null
  }
}

export const nativeMacOSAddon = loadNativeModule()
